### ISSUE TITLE
Why is the published version of the documentation very different than this repo?

### ISSUE THREAD

**Issue by DanielLoyAugmedix** [awsdocs/aws-sdk-for-javascript-v3#56]
There are a few minor fixes that I would like to make a PR for on the published version of the docs (specifically https://github.com/awsdocs/aws-sdk-for-javascript-v3/blob/main/doc_source/dynamodb-example-table-read-write.md):

But this is what I see on the v3 docs page:

![Screen Shot 2021-06-23 at 11 39 56 AM](https://user-images.githubusercontent.com/58446689/123151048-e79b8f00-d417-11eb-8777-d42bf48ed45d.png)

But this is what is on top of master (https://github.com/awsdocs/aws-sdk-for-javascript-v3/blob/846eb3664690104149462f25c869baf99f0ce3fd/doc_source/dynamodb-example-table-read-write.md) :
![Screen Shot 2021-06-23 at 11 41 42 AM](https://user-images.githubusercontent.com/58446689/123151160-0a2da800-d418-11eb-8f36-2fa58bd63e38.png)

They are quite divergent, which makes community contribution to this project impossible. 

(Perfectly willing to believe that I'm the idiot and I found an outdated public version of the repo. But then, where is the current/published version that we can fork?)

**Comment by orozcoadrian** [comment]
I'm not a maintainer of this repo, but I do see that recently merged PRs have been merged into `main`. So my guess is that you should use `main` instead of `master`.
Also, the contents from your `main` link match the published docs: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-example-table-read-write.html#dynamodb-example-table-read-write-getting-an-item

**Comment by brmur** [comment]
This repo is manually updated regularly, but occassionally there's a lag between updates to the main site and this github repo.
